# Generated by Django 3.0.3 on 2020-07-27 20:26

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='create_date',
            field=models.DateTimeField(default=datetime.datetime(2020, 7, 27, 20, 26, 2, 169974, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='post',
            name='create_field',
            field=models.DateTimeField(default=datetime.datetime(2020, 7, 27, 20, 26, 2, 168977, tzinfo=utc)),
        ),
    ]
